services:
  - type: web
    name: kode-iot-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: API_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
